"""Add uq_images_album_origin unique constraint on (album_id, yupoo_origin_url)

Revision ID: be3675542bee
Revises: fa672223429c
Create Date: 2026-08-29 23:27:30.835182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3675542bee'
down_revision: Union[str, None] = 'fa672223429c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_images_album_origin', 'images', ['album_id', 'yupoo_origin_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_images_album_origin', 'images', type_='unique')
    # ### end Alembic commands ###
