"""Refactor to many-to-many categories

Revision ID: fa672223429c
Revises: 6b2dcf147d3c
Create Date: 2026-08-27 13:56:24.216601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa672223429c'
down_revision: Union[str, None] = '6b2dcf147d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_category_association',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('album_id', 'category_id')
    )
    op.add_column('albums', sa.Column('cover_url', sa.Text(), nullable=True))
    op.drop_constraint('albums_category_id_fkey', 'albums', type_='foreignkey')
    op.drop_column('albums', 'category_id')
    op.drop_constraint('categories_parent_id_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('categories_parent_id_fkey', 'categories', 'categories', ['parent_id'], ['id'])
    op.add_column('albums', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('albums_category_id_fkey', 'albums', 'categories', ['category_id'], ['id'])
    op.drop_column('albums', 'cover_url')
    op.drop_table('album_category_association')
    # ### end Alembic commands ###
